version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - run:
          name: Deploying S3ContinuousDeploy.
          command: echo Deploying S3ContinuousDeploy.
      - run:
          name: Install awscli
          command: |
                    sudo apt-get update
                    sudo apt-get install -y python-pip python-dev
                    sudo pip install awscli
                    aws --version
                    node -v
                    npm -v
      - deploy:
          name: Deploy to S3 if branch is Master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync /home/ubuntu/S3ContinuousDeploy s3://actoprohld --delete
            fi
